### ISSUE TITLE
"path" handling in interfaces

### ISSUE THREAD

**Issue by alexhuth** [gallantlab/cottoncandy#17]
Currently a lot of things in the interface object assume that objects are stored using a unix-like path syntax. This makes s3cmd and s3fs play nicely, and it's pretty widely used for s3 stuff. But how paths are currently constructed inside `BasicInterface` is inconsistent, and could potentially create issues.

One method is by joining together path strings using a `SEPARATOR` (defined as "/" in cc.interfaces). For example, `name = SEPARATOR.join([object_name, k])`. The value of `SEPARATOR` is also used to delimit "directories" in the FileSystemInterface. This is fine, but runs the risk of ending up with doubled slashes (e.g. `SEPARATOR.join(["fuck/", "you"])` gives `fuck//you`). Also it's annoying to get elsewhere if you want to make portable code (e.g. `from cottoncandy.interfaces import SEPARATOR`, etc.).

The other method that's used currently is `os.path.join` (e.g. `path = os.path.join(object_root, subdir)`). This function removes double slashes, but has the downside of not being portable: `os.path.join` will have different behavior on different operating systems (in windows it will use "\" instead of "/").

To make things consistent and portable, I suggest we add a `join` method to `BasicInterface` that mimics the behavior of `os.path.join` but with our specified `SEPARATOR`. Thoughts?

**Comment by anwarnunez** [comment]
yes, plz
