### ISSUE TITLE
turning on debug logging and then uploading large matrices results in hundreds of megabytes of log being written to console

### ISSUE THREAD

**Issue by alexhuth** [gallantlab/cottoncandy#18]
I often use the `logging` module to control how much info is spit to screen. I just discovered that this plays poorly with cc. With `logging.basicConfig(level=logging.DEBUG)`, boto seems to print the entirety of each uploaded object (in hex) to the console. This sucks ass.

`DEBUG:botocore.hooks:Event before-parameter-build.s3.UploadPart: calling handler <function validate_bucket_name at 0x7f8ac2716398>
DEBUG:botocore.hooks:Event before-call.s3.UploadPart: calling handler <function conditionally_calculate_md5 at 0x7f8ac2716320>
DEBUG:botocore.hooks:Event before-call.s3.UploadPart: calling handler <function add_expect_header at 0x7f8ac27167d0>
DEBUG:botocore.endpoint:Making request for <botocore.model.OperationModel object at 0x7f8ac2294950> (verify_ssl=True) with params: {'body': '\x1f\x8b\x08\x00C^\xfdW\x02\xff,\x9c{<\xd3\xff\x17\xc7\x17]DeIHd\x92k*$D8\xeew\xe6>\xb7\xd90\x97\xa2D\xa4\xab\xa1\x0bQ\` etc etc

**Comment by alexhuth** [comment]
I knew I'd seen this somewhere.. turns out @marklescroart solved it and made a pull request that anwar was balking on. Now merged!

**Comment by anwarnunez** [comment]
issue is upstream. boto became super verbose a few versions ago. also, user can set this at their script level... 
this fix is fine for now, I guess. eventually, this kinda thing can be controlled by config.
