### ISSUE TITLE
docs in README

### ISSUE THREAD

**Issue by alexhuth** [gallantlab/cottoncandy#53]
The docs right now are quite nice: http://gallantlab.github.io/cottoncandy/

but the README.md leaves a lot to be desired. I think it'd be great if a lot of the content from the front page of the docs (Install, Getting Started, basic usage) was replicated in the README.

I would do this myself and make a PR if I had the gumption.. sorry

**Comment by anwarnunez** [comment]
good point! I'll take care of it
