### ISSUE TITLE
aesthetics

### ISSUE THREAD

**Issue by anwarnunez** [gallantlab/cottoncandy#6]
ideas for logo: 
http://20px.com/wp-content/uploads/2013/02/unicorn_pooping_rainbow_sq.jpg
https://media.giphy.com/media/tTyTbFF9uEbPW/giphy.gif

i'm leaning towards bright pink cotton candy thing puking a rainbow. if we can get a unicorn in there, even better.

**Comment by candytaco** [comment]
<img width="1439" alt="cc2" src="https://user-images.githubusercontent.com/17423004/43179059-9f1ca3b0-8f85-11e8-8f75-587062e75339.png">
