### ISSUE TITLE
test on conda environment

### ISSUE THREAD

**Issue by anwarnunez** [gallantlab/cottoncandy#65]
check that pip and setup.py installs on Linux and configuration files are generated.

**Comment by cmcneil** [comment]
I did the following steps, and everything works. However I did have to install `boto3` and numpy by hand, as they didn't install automatically on cc install.

```
conda create -n py36 python=3.6 anaconda
conda activate py36
which pip
# returns <MY_MINICONDA_PATH>/envs/py36/bin/pip
pip install boto3
conda install numpy
pip install cottoncandy
python
>> import cottoncandy
# automatically generates config
```

**Comment by cmcneil** [comment]
PS Also tried in python 3.5 and python 2.7 (Intel distro) environments.

**Comment by anwarnunez** [comment]
thanks for testing @cmcneil !

@vsoch: My bad. The config file is created upon first import! I think your installation will work. Just try importing cottoncandy and that will create the config. Let me know.

**Comment by vsoch** [comment]
:snake:
