### ISSUE TITLE
Uploading large arrays doesn't use compression

### ISSUE THREAD

**Issue by the-moliver** [gallantlab/cottoncandy#9]
Perhaps use the `tarfile` or `zipfile` libraries instead of `gzip`

**Comment by alexhuth** [comment]
To be more precise, `upload_raw_array` doesn't compress things with more than 2**31 bytes (2.1G). There's a comment that says "avoid zlib issues". @anwarnunez remember why?

**Comment by anwarnunez** [comment]
As I remember, it relates to this issue: https://bugs.python.org/issue23306

**Comment by anwarnunez** [comment]
fixed by #61
